# -*- coding: utf-8 -*-
"""Untitled70.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DpCIh4BDF33rGnO2CgrcSbdisAeXmbbJ
"""

"""
Agro-IA Audit: Maestro de Inferencia y Detección de Anomalías
Optimización de Clay v1.5 para Maíz en Argentina
Autor: Darío Nicolás Sánchez Leguizamón
"""

import os, torch, numpy as np, pandas as pd, geopandas as gpd, glob
import matplotlib.pyplot as plt
from datetime import datetime

# Configuración del Entorno
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PATH_GEOJSON = 'lote_pivote.geojson'

def build_clay_refined():
    """
    Refactorización de la capa patch_embed para 10 bandas de Sentinel-2.
    Resuelve la incompatibilidad nativa del modelo original.
    """
    import timm
    model = timm.create_model("vit_large_patch16_224", pretrained=False, num_classes=0)
    old_proj = model.patch_embed.proj
    model.patch_embed.proj = torch.nn.Conv2d(10, old_proj.out_channels, 7, 16)
    return model.to(DEVICE).eval()

def run_audit_pipeline():
    model = build_clay_refined()
    # Buscamos los chips reales procesados por el motor de Data-Crew
    chip_files = sorted(glob.glob("data/chips/*/*.npz"))

    if not chip_files:
        raise FileNotFoundError("🚨 Chips no detectados. Asegúrese de ejecutar el pipeline de fetch/chip.")

    results = []
    with torch.no_grad():
        for f in chip_files:
            date_str = os.path.basename(f).replace('.npz', '')
            # NORMALIZACIÓN 1/10000: Hallazgo técnico para recuperar variabilidad
            data = np.load(f)['pixels'][:10, :, :].astype('float32') / 10000.0
            tensor = torch.from_numpy(data).unsqueeze(0).to(DEVICE)

            emb = model(tensor).cpu().numpy().flatten()
            results.append({"date": datetime.strptime(date_str, '%Y-%m-%d'), "embedding": emb})

    return pd.DataFrame(results).sort_values("date")

def generate_visual_report(df):
    # Cálculo de trayectoria y Scoring Adaptativo (Z-Score)
    ref_emb = df['embedding'].iloc[0]
    df['distance'] = df['embedding'].apply(lambda x: np.linalg.norm(x - ref_emb))
    diffs = df['distance'].diff().fillna(0)
    df['z_score'] = (diffs - diffs.mean()) / (diffs.std() + 1e-6)

    # Plot de Vigor
    plt.figure(figsize=(14, 6))
    plt.plot(df['date'], df['distance'], marker='o', color='#2ecc71', lw=2, label="Vigor (Clay Space)")
    anomalies = df[df['z_score'].abs() > 1.2]
    for _, row in anomalies.iterrows():
        plt.scatter(row['date'], row['distance'], color='red', s=150, zorder=5)
    plt.title("Auditoría de Campaña: Dinámica Espectral Lote Pivote")
    plt.grid(True, ls=':', alpha=0.4)
    plt.savefig('output/trayectoria_vigor.png')
    plt.show()

    # Inspección Visual del punto crítico
    if not anomalies.empty:
        top_date = anomalies.loc[anomalies['z_score'].abs().idxmax(), 'date'].strftime('%Y-%m-%d')
        img_path = glob.glob(f"data/chips/*/{top_date}.npz")[0]
        pix = np.load(img_path)['pixels']
        rgb = np.stack([pix[2], pix[1], pix[0]], axis=-1)
        rgb = np.clip(rgb / 3000 * 255, 0, 255).astype(np.uint8)

        plt.figure(figsize=(6, 6))
        plt.imshow(rgb)
        plt.title(f"Inspección Visual: Anomalía detectada el {top_date}")
        plt.axis('off')
        plt.savefig('output/inspeccion_visual_real.png')
        plt.show()

if __name__ == "__main__":
    df_final = run_audit_pipeline()
    generate_visual_report(df_final)